Repository stackhpc/stackhpc-kayobe-config, pull requests merged in 2023-02, with the labels that each got.

#383 feat: automatic update of workflows stackhpc/victoria
  .github/workflows/tag-and-release.yml
Labels: stackhpc-ci, workflows

#382 feat: automatic update of workflows stackhpc/wallaby
  .github/workflows/tag-and-release.yml
Labels: stackhpc-ci, workflows

#381 feat: automatic update of workflows stackhpc/xena
  .github/workflows/tag-and-release.yml
Labels: stackhpc-ci, workflows

#391 fix: task would fail to delegate and run on host
  etc/kayobe/ansible/nova-compute-drain.yml
Labels: bug

#396 Fix default when ANSIBLE_SERIAL not set
  etc/kayobe/ansible/reboot.yml
Labels: wallaby

#397 Refresh ubuntu container images
  etc/kayobe/kolla.yml
  etc/kayobe/kolla/globals.yml
  releasenotes/notes/release-train-02-2023-package-refresh-ubuntu-a9fe8a1c3c2f2796.yaml
Labels: wallaby

#402 Refresh ubuntu container images
  etc/kayobe/ansible/nova-compute-drain.yml
  etc/kayobe/kolla.yml
  etc/kayobe/kolla/globals.yml
  releasenotes/notes/release-train-02-2023-package-refresh-ubuntu-a9fe8a1c3c2f2796.yaml
Labels: xena

#407 Bump neutron containers to support DellOS10/trunking
  etc/kayobe/kolla/globals.yml
  releasenotes/notes/adds-support-for-trunk-ports-7301a258dca0c469.yaml
Labels: xena

#408 Bump neutron containers to support DellOS10/trunking
  etc/kayobe/kolla/config/grafana.ini
  etc/kayobe/kolla/globals.yml
  releasenotes/notes/adds-support-for-trunk-ports-7301a258dca0c469.yaml
Labels: yoga
