Repository stackhpc/stackhpc-kayobe-config, pull requests merged in 2024-10, with the labels that each got.

#1315 feat: bump `multinode` workflow
  .github/workflows/stackhpc-multinode-periodic.yml
  .github/workflows/stackhpc-multinode.yml
Labels: bug

#1320 Disable Seed firewalld when using OVS
  etc/kayobe/environments/ci-multinode/seed.yml
Labels: bug, antelope

#1325 2024.1 upgrade doc additions
  doc/source/operations/upgrading-openstack.rst
Labels: documentation

#830 Update and supplement missing information on instructions
  doc/source/contributor/package-updates.rst
Labels: documentation

#1329 Add delay between RabbitMQ upgrades
  doc/source/operations/upgrading-openstack.rst
Labels: documentation, Caracal

#1340 INFRA-841 add tags for updated `Ironic` containers
  etc/kayobe/kolla-image-tags.yml
  releasenotes/notes/fix-ossa-2024-004-f732e58c12e26785.yaml
Labels: security

#1341 INFRA-841 add tags for updated `Ironic` containers
  etc/kayobe/kolla-image-tags.yml
  releasenotes/notes/fix-ossa-2024-004-f732e58c12e26785.yaml
Labels: security

#1355 Pin Magnum to Antelope for both Ubuntu and Rocky
  etc/kayobe/kolla/globals.yml
Labels: Caracal
