Repository stackhpc/stackhpc-kayobe-config, pull requests merged in 2024-12, with the labels that each got.

#1395 enable extra ipa collectors only when building ipa
  etc/kayobe/ipa.yml
Labels: backport

#1392 Fix Bifrost templating bug on httpboot config
  etc/kayobe/kolla-image-tags.yml
  etc/kayobe/kolla.yml
  releasenotes/notes/fix-bifrost-httpboot-config-templating-0488dd14d15d65e4.yaml
Labels: bug, Caracal

#1046 Use Openstack dashboard as Grafana home dashboard
  etc/kayobe/kolla/config/grafana/dashboards/openstack/openstack.json
  etc/kayobe/kolla/config/grafana/grafana_home_dashboard.json
  releasenotes/notes/grafana-openstack-dashboard-e99a6a44e927363f.yaml
Labels: Caracal, monitoring

#1396 Add auto-label bot initial config
  .github/auto-label.yaml
Labels: Caracal, workflows

#1390 Generalise host image playbooks
  .github/workflows/overcloud-host-image-build.yml
  .github/workflows/overcloud-host-image-promote.yml
  etc/kayobe/ansible/pulp-artifact-promote.yml
  etc/kayobe/ansible/pulp-artifact-upload.yml
  etc/kayobe/ansible/pulp-host-image-download.yml
  etc/kayobe/environments/ci-builder/stackhpc-ci.yml
Labels: Caracal, size: m

#1401 Correct redfish_exporter_default_username
  etc/kayobe/stackhpc-monitoring.yml
Labels: Caracal, backport, size: xs

#1083 Doc from openstack admin guide
  doc/source/configuration/cephadm.rst
  doc/source/configuration/ci-cd.rst
  doc/source/configuration/lvm.rst
  doc/source/configuration/monitoring.rst
  doc/source/configuration/release-train.rst
  doc/source/configuration/swap.rst
  doc/source/configuration/vault.rst
  doc/source/configuration/wazuh.rst
  doc/source/contributor/pre-commit.rst
  doc/source/operations/bifrost-hardware-inventory-management.rst
  doc/source/operations/ceph-management.rst
  doc/source/operations/control-plane-operation.rst
  doc/source/operations/customising-horizon.rst
  doc/source/operations/gpu-in-openstack.rst
  doc/source/operations/hotfix-playbook.rst
  doc/source/operations/index.rst
  doc/source/operations/migrating-vm.rst
  doc/source/operations/nova-compute-ironic.rst
  doc/source/operations/octavia.rst
  doc/source/operations/openstack-projects-and-users-management.rst
  doc/source/operations/openstack-reconfiguration.rst
  doc/source/operations/secret-rotation.rst
  doc/source/operations/upgrading-openstack.rst
Labels: documentation, antelope, Caracal, size: xl

#1407 Correct redfish_exporter_default_username
  etc/kayobe/stackhpc-monitoring.yml
Labels: antelope, size: xs

#1409 Rebuilt Neutron containers to fix OSSA-2024-005
  etc/kayobe/kolla-image-tags.yml
  releasenotes/notes/OSSA-2024-005-74fc3c536cde645f.yaml
Labels: size: s

#1418 docs: Synchronise TEMPEST_CONCURRENCY with reality
  doc/source/operations/tempest.rst
Labels: documentation, size: xs

#1410 Caracal: Update Let's Encrypt images
  etc/kayobe/kolla-image-tags.yml
  releasenotes/notes/add-letsencrypt-eab-support-807bdc4078d3114d.yaml
Labels: enhancement, Caracal, size: xs

#1417 Fix ironic-inspector blackbox backend endpoint
  etc/kayobe/kolla/inventory/group_vars/prometheus-blackbox-exporter
  releasenotes/notes/ironic-inspector-blackbox-backend-ff1bd68297435a36.yaml
Labels: size: xs

#1421 Add cherry-pick-bot.yml
  .github/cherry-pick-bot.yml
Labels: workflows, size: xs

#1420 Update Cinder container images to fix bug 1823445
  etc/kayobe/kolla-image-tags.yml
  releasenotes/notes/cinder-bug-1823445-5d07997488bc2416.yaml
Labels: size: xs

#1423 Enable preservePullRequestTitle for cherry bot
  .github/cherry-pick-bot.yml
Labels: workflows, size: xs

#1425 Document Heat removal in 2024.1 OpenStack upgrade
  doc/source/operations/upgrading-openstack.rst
Labels: documentation, size: s

#1424 Alert rule for active routers on ML2/OVS
  etc/kayobe/kolla/config/prometheus/openstack.rules
  releasenotes/notes/adds-alert-for-active-routers-91281912213692c9.yaml
Labels: monitoring, size: s

#1414 IPA build workflow
  .github/workflows/ipa-image-build.yml
  .github/workflows/ipa-image-promote.yml
  doc/source/configuration/index.rst
  doc/source/configuration/ipa.rst
  etc/kayobe/ansible/pulp-artifact-upload.yml
  etc/kayobe/bifrost.yml
  etc/kayobe/environments/ci-builder/inventory/hosts
  etc/kayobe/environments/ci-builder/stackhpc-ci.yml
  etc/kayobe/ipa.yml
  etc/kayobe/pulp-ipa-image-versions.yml
  etc/kayobe/stackhpc-ipa-images.yml
  releasenotes/notes/ipa-build-workflow-cde24f3b9e3e0667.yaml
Labels: documentation, enhancement, Caracal, workflows, size: l

#1388 INFRA-871 Remove angular plugins from Grafana
  etc/kayobe/kolla-image-tags.yml
  etc/kayobe/kolla.yml
  etc/kayobe/trivy/allowed-vulnerabilities.yml
  releasenotes/notes/grafana-remove-angular-plugins-1c10e83ddb6556f4.yaml
Labels: Caracal, monitoring, size: s

#1428 yoga: Stop building cinder from StackHPC fork
  etc/kayobe/kolla.yml
Labels: size: xs

#1429 Revert "zed: Build Glance from StackHPC fork"
  etc/kayobe/kolla.yml
Labels: size: xs

#1426 Amending paths to match Ark
  etc/kayobe/pulp.yml
Labels: bug, Caracal, size: xs

#1430 Add RL9.5 support
  etc/kayobe/kolla-image-tags.yml
  etc/kayobe/pulp-repo-versions.yml
  etc/kayobe/pulp.yml
  releasenotes/notes/rl95-6cbdf902e30502bf.yaml
Labels: Caracal, size: m

#1405 Update auto-label config
  .github/auto-label.yaml
Labels: workflows, size: m

#1433 Fix playbook stopping wrong services
  etc/kayobe/ansible/stop-openstack-services.yml
Labels: bug, ansible, size: xs
