Repository stackhpc/stackhpc-kayobe-config, pull requests merged in 2024-08, with the labels that each got.

#1208 fix: add missing endpoints for `Grafana` and `Horizon`
  etc/kayobe/kolla/inventory/group_vars/prometheus-blackbox-exporter
Labels: bug

#1201 docs: Update release train image
  doc/source/_static/images/release-train.svg
Labels: documentation

#1232 fix: typo in playbook run command
  doc/source/configuration/monitoring.rst
Labels: documentation, yoga
