Repository stackhpc/stackhpc-kayobe-config, pull requests merged in 2024-01, with the labels that each got.

#871 Add kolla config merging to upgrade docs
  doc/source/operations/upgrading.rst
Labels: documentation

#828 Update to Rocky Linux 9.3
  etc/kayobe/kolla/globals.yml
  etc/kayobe/pulp-repo-versions.yml
  etc/kayobe/pulp.yml
  releasenotes/notes/add-rocky-9.3-repos-454c2f825e088417.yaml
Labels: yoga

#878 Fix issue with GRUB defaulting to an old kernel
  etc/kayobe/ansible/reset-bls-entries.yml
  releasenotes/notes/reset-bls-entries-b2bded62c5887937.yaml
Labels: bug
