Repository stackhpc/stackhpc-kayobe-config, pull requests merged in 2025-03, with the labels that each got.

#1548 Automate Kolla version updates (2023.1)
  .github/workflows/update-dependencies.yml
  etc/kayobe/stackhpc.yml
  releasenotes/notes/kolla-dependency-workflow-6ff5520ee0ab8e15.yaml
  requirements.txt
Labels: workflows, size: m

#1495 Pin remaining Ansible dependencies
  etc/kayobe/ansible/requirements.yml
  releasenotes/notes/pin-deps-dbe52c49e945daf5.yaml
Labels: ansible, size: xs

#1519 Update docs to reference Ubuntu Noble, not Jammy
  .readthedocs.yaml
  doc/source/configuration/host-images.rst
  doc/source/configuration/ipa.rst
  doc/source/configuration/release-train.rst
  doc/source/configuration/security-hardening.rst
  doc/source/contributor/environments/aufn-ceph.rst
  doc/source/contributor/environments/ci-aio.rst
  doc/source/contributor/environments/ci-builder.rst
  doc/source/contributor/environments/ci-multinode.rst
  doc/source/contributor/testing-ci-automation.rst
  tools/ubuntu-upgrade-infra-vm.sh
  tools/ubuntu-upgrade-overcloud.sh
  tools/ubuntu-upgrade-seed-hypervisor.sh
  tools/ubuntu-upgrade-seed.sh
Labels: documentation, size: m

#1552 Kolla dependency updates on non-default branches
  .github/workflows/stackhpc-update-kolla.yml
  .github/workflows/update-dependencies.yml
  releasenotes/notes/kolla-update-fixes-5ff55225ce85441f.yaml
Labels: workflows, size: m

#1544 Fix "Max Inlet Temp" time series chart
  etc/kayobe/kolla/config/grafana/dashboards/openstack/redfish.json
  releasenotes/notes/redfish-dashboard-fix-inlet-temp-91a7018adb2e1763.yaml
Labels: monitoring, size: xs

#1557 Fix broken links & ensure all kayobe, kolla & KA docs links use extlinks
  doc/source/configuration/cephadm.rst
  doc/source/configuration/ci-cd.rst
  doc/source/configuration/cloudkitty.rst
  doc/source/index.rst
  releasenotes/notes/fix-broken-links-dcd128c8e211b2b8.yaml
Labels: documentation, size: s

#1558 Cherry pick fix broken links to 2023.1
  doc/source/configuration/cephadm.rst
  doc/source/configuration/ci-cd.rst
  doc/source/configuration/cloudkitty.rst
  doc/source/index.rst
  releasenotes/notes/fix-broken-links-150bf2dd009123d1.yaml
Labels: documentation, size: s

#1570 Bump neutron images to fix #2097770 (For stackhpc/2023.1)
  etc/kayobe/kolla-image-tags.yml
  releasenotes/notes/revert-track-all-interfaces-in-keepalived-371eea147fbebf36.yaml
Labels: bug, antelope, size: s, kolla

#1559 Bump image tags for CVE-2024-53916 (Zed)
  .github/workflows/stackhpc-build-kayobe-image.yml
  .github/workflows/stackhpc-pull-request.yml
  etc/kayobe/kolla-image-tags.yml
  releasenotes/notes/neutron-cve-068b1299a304ee12.yaml
Labels: size: s, kolla

#1553 Bump image tags for CVE-2024-53916
  .github/workflows/stackhpc-build-kayobe-image.yml
  .github/workflows/stackhpc-pull-request.yml
  releasenotes/notes/neutron-cve-37a7821967a36779.yaml
Labels: size: s, kolla

#1560 feat: use `include_tags` for kolla repositories
  etc/kayobe/pulp.yml
  releasenotes/notes/use-include-tags-for-client-pulp-cf46d328b30162be.yaml
Labels: size: s

#1571 Fix brackets in fluentd opensearch config
  etc/kayobe/kolla/config/fluentd/output/03-opensearch.conf
  releasenotes/notes/fix-fluentd-opensearch-template-14bde9b6d5a723f8.yaml
Labels: monitoring, size: xs

#1575 Update heat removal docs
  doc/source/operations/upgrading-openstack.rst
Labels: documentation, size: xs

#1573 Docs from Openstack admin guide
  doc/source/configuration/cephadm.rst
  doc/source/configuration/ci-cd.rst
  doc/source/configuration/lvm.rst
  doc/source/configuration/monitoring.rst
  doc/source/configuration/release-train.rst
  doc/source/configuration/vault.rst
  doc/source/configuration/wazuh.rst
  doc/source/contributor/pre-commit.rst
  doc/source/operations/bifrost-hardware-inventory-management.rst
  doc/source/operations/ceph-management.rst
  doc/source/operations/control-plane-operation.rst
  doc/source/operations/customising-horizon.rst
  doc/source/operations/gpu-in-openstack.rst
  doc/source/operations/hotfix-playbook.rst
  doc/source/operations/index.rst
  doc/source/operations/migrating-vm.rst
  doc/source/operations/nova-compute-ironic.rst
  doc/source/operations/octavia.rst
  doc/source/operations/openstack-projects-and-users-management.rst
  doc/source/operations/openstack-reconfiguration.rst
  doc/source/operations/secret-rotation.rst
  doc/source/operations/upgrading-openstack.rst
Labels: documentation, Caracal, size: xl, Epoxy

#1572 Filter out interfaces that don't matter for packet drops.
  etc/kayobe/kolla/config/prometheus/ceph.rules
Labels: monitoring, size: xs

#1574 Fix ceph-rgw blackbox endpoint enabling
  etc/kayobe/kolla/inventory/group_vars/prometheus-blackbox-exporter
  releasenotes/notes/fix-ceph-rgw-blackbox-endpoint-7af02679b3fd093d.yaml
Labels: monitoring, size: xs

#1582 update ovs/ovn in RL9 in antelope
  etc/kayobe/kolla-image-tags.yml
  etc/kayobe/pulp-repo-versions.yml
Labels: size: s, kolla

#1581 [CI] Fixes update Kolla versions running on clones
  .github/workflows/stackhpc-update-kolla.yml
Labels: workflows, size: xs

#1578 Docs: add warning about Ceph when updating packages
  doc/source/operations/upgrading-openstack.rst
Labels: documentation, size: s

#1584 Fix download of IPA images from Ark in Bifrost
  etc/kayobe/kolla-image-tags.yml
  etc/kayobe/kolla/config/bifrost/bifrost.yml
  releasenotes/notes/bifrost-fix-ipa-auth-9d0e0c3b948b5850.yaml
Labels: size: s

#1583 Nit: Add .git to all Github Repos in kolla.yml
  etc/kayobe/kolla.yml
Labels: size: s, kolla

#1585 Fix Kolla dependencies update schedule
  .github/workflows/stackhpc-update-kolla.yml
  .github/workflows/update-dependencies.yml
Labels: workflows, size: s

#1587 Fix typo in octavia-amphora-image-register playbook
  etc/kayobe/ansible/octavia-amphora-image-register.yml
Labels: ansible, size: xs

#1593 Replace 'stackhpc-ci' label with 'automated'
  .github/workflows/update-dependencies.yml
Labels: workflows, size: xs
