Repository stackhpc/stackhpc-kayobe-config, pull requests merged in 2025-07, with the labels that each got.

#1735 Revert Pulp Squeezer version bump
  etc/kayobe/ansible/pulp-artifact-upload.yml
  etc/kayobe/ansible/requirements.yml
  releasenotes/notes/ansible-requirements-bump-89313038efba83b3.yaml
Labels: ansible, size: m

#1738 Epoxy - Add AlmaLinux ProxySQL repo definitions
  etc/kayobe/environments/ci-aio/stackhpc-ci.yml
  etc/kayobe/environments/ci-builder/stackhpc-ci.yml
  etc/kayobe/environments/ci-multinode/stackhpc-ci.yml
  etc/kayobe/kolla-image-tags.yml
  etc/kayobe/kolla.yml
  etc/kayobe/pulp-repo-versions.yml
  etc/kayobe/pulp.yml
  etc/kayobe/stackhpc.yml
  releasenotes/notes/proxysql-repo-definition-0400b08e4455e1c0.yaml
Labels: size: s, kolla

#1747 CI: revert openbao changes for multinode
  etc/kayobe/environments/ci-multinode/stackhpc-monitoring.yml
  etc/kayobe/environments/ci-multinode/tempest.yml
Labels: size: xs

#1750 Add get-cloud-facts.yml to gather deployment info
  etc/kayobe/ansible/get-cloud-facts.yml
Labels: ansible, size: m

#1322 add multiarch (aarch64 + amd64) container image builds for R9
  .github/workflows/stackhpc-container-image-build.yml
  etc/kayobe/environments/ci-aio/stackhpc-ci.yml
  etc/kayobe/environments/ci-builder/stackhpc-ci.yml
  etc/kayobe/environments/ci-multinode/stackhpc-ci.yml
  etc/kayobe/kolla-image-tags.yml
  etc/kayobe/kolla.yml
  etc/kayobe/pulp-repo-versions.yml
  etc/kayobe/pulp.yml
  etc/kayobe/stackhpc.yml
  tools/multiarch-manifests.sh
  tools/scan-images.sh
Labels: enhancement, Caracal, size: l, arm64

#1768 Bump kolla to stackhpc/18.7.0.5
  etc/kayobe/stackhpc.yml
Labels: size: xs

#1773 Push DOCA OFED modules to release
  etc/kayobe/ansible/push-ofed.yml
Labels: ansible, size: xs

#1776 Remove Zuul configuration until it is properly configured
  zuul.d/project.yaml
Labels: size: s

#1782 docs: update certificate rotation warning
  doc/source/configuration/openbao.rst
  doc/source/configuration/vault.rst
Labels: documentation, size: s

#1775 feat: increase `TTL` for `TLS` role
  etc/kayobe/inventory/group_vars/all/openbao.yml
  etc/kayobe/inventory/group_vars/all/vault
  releasenotes/notes/increase-tls-ttl-c1eba5cca7767d0f.yaml
Labels: size: s

#1794 Update Epoxy doc to use RabbitMQ 4.1
  doc/source/operations/upgrading-openstack.rst
Labels: documentation, size: s

#1734 Various AUFN-related changes for Epoxy
  etc/kayobe/ansible/purge-command-not-found.yml
  etc/kayobe/apt.yml
  etc/kayobe/bifrost.yml
  etc/kayobe/environments/aufn-ceph/a-universe-from-nothing.sh
  etc/kayobe/environments/aufn-ceph/compute.yml
  etc/kayobe/environments/aufn-ceph/controllers.yml
  etc/kayobe/environments/aufn-ceph/inventory/group_vars/all/lvm.yml
  etc/kayobe/environments/aufn-ceph/stackhpc-ci.yml
  etc/kayobe/environments/aufn-ceph/stackhpc.yml
  etc/kayobe/environments/aufn-ceph/storage.yml
  etc/kayobe/environments/aufn-ceph/tenks.yml
  etc/kayobe/environments/aufn-ceph/time.yml
  etc/kayobe/kolla-image-tags.yml
  etc/kayobe/kolla.yml
  etc/kayobe/kolla/config/bifrost/bifrost.yml
  etc/kayobe/pulp-host-image-versions.yml
  etc/kayobe/pulp-ipa-image-versions.yml
  etc/kayobe/pulp-repo-versions.yml
  requirements.txt
Labels: ansible, size: m, kolla

#1801 Bump Ceph to v19.2.3
  etc/kayobe/cephadm.yml
  releasenotes/notes/ceph-19.2.3-1b0af47e75bb7456.yaml
Labels: size: xs

#1790 [2025.1] add aarch64 container image builds for R9
  .github/workflows/stackhpc-container-image-build.yml
  etc/kayobe/environments/ci-aio/stackhpc-ci.yml
  etc/kayobe/environments/ci-builder/stackhpc-ci.yml
  etc/kayobe/environments/ci-multinode/stackhpc-ci.yml
  etc/kayobe/kolla.yml
  etc/kayobe/pulp-repo-versions.yml
  etc/kayobe/pulp.yml
  etc/kayobe/stackhpc.yml
  releasenotes/notes/rocky9-multiarch-builds-17671005bfb73dc9.yaml
  tools/multiarch-manifests.sh
  tools/scan-images.sh
Labels: workflows, size: l, kolla

#1810 Refresh all Kolla container images
  etc/kayobe/kolla-image-tags.yml
  releasenotes/notes/image-refresh-043917ef996c96b7.yaml
Labels: size: s, kolla
